### PR TITLE
Added 'last_login' to 'LimitedUser' schema

### PR DESCRIPTION
**Pull request by MineTech13**
After my missunderstanding what i needed to do in the last pull request and the amount of changes that happend i decived to recheck what still is diffrent and create a new merge request on the current main ^^ thanks for the one who helped clarifying what i missunderstood on discord ^^ i hope i did it correctly this time just added the last_login field that is still missing since my last pull request

### CODE REVIEW

**Comment by jellejurre** [comment]
if you're re-making it from https://github.com/vrchatapi/specification/pull/369/files, do you have a reason to not also add last_mobile?

**Comment by MineTech13** [comment]
@jellejurre "last_mobile" seems to gotten added already by someone else while I was on vacation so I skipped it

**Comment by jellejurre** [comment]
fair enough

**Review by jellejurre — APPROVED** [review]
Confirmed to work on C# api

**Pull request merged**
