### PR TITLE
fix(groups): add pagination parameters for requests and invites

### PR DESCRIPTION
**Pull request by ttshivers**
Add pagination parameters for group requests and invites.

### CODE REVIEW

**Review by ariesclark — APPROVED** [review]

**Comment by ttshivers** [comment]
Thanks for merging. Can there be a new release with these changes too?

**Comment by ariesclark** [comment]
> Thanks for merging. Can there be a new release with these changes too?

Will do a release shortly.

**Comment by ttshivers** [comment]
Any update about a new release?

**Comment by ariesclark** [comment]
> Any update about a new release?

Waited for an approval from another contributor.
https://github.com/vrchatapi/specification/pull/288

**Pull request merged**
