### PR TITLE
Remove storeId

### PR DESCRIPTION
**Pull request by jellejurre**

### CODE REVIEW

**Comment by ariesclark** [comment]
If the property never occurs, I would prefer to remove it entirely to avoid having properties that are "lost to time" in the scheme.

**Comment by Rexios80** [comment]
Getting this in the Dart SDK

```
DioException (DioException [unknown]: null
Error: CheckedFromJsonException
Could not create `LimitedWorld`.
There is a problem with "storeId".
Required keys are missing: storeId.)
```

**Comment by jellejurre** [comment]
Fair enough, if they come back I suppose we'll just readd them

**Comment by jellejurre** [comment]
> Getting this in the Dart SDK
> 
> ```
> DioException (DioException [unknown]: null
> Error: CheckedFromJsonException
> Could not create `LimitedWorld`.
> There is a problem with "storeId".
> Required keys are missing: storeId.)
> ```

This is the result before this pr, I added storeId as a required argument because it seemed to always be there, but then they removed it, so now you get "required arguement is missing", hence we're removing it again

**Review by ariesclark — APPROVED** [review]

**Pull request merged**
