### PR TITLE
fix(instance): specify that roleRestricted is nullable

### PR DESCRIPTION
**Pull request by ttshivers**
Specify that roleRestricted is nullable as detected through observation.

Fixes: #323

### CODE REVIEW

**Comment by Rexios80** [comment]
Hold on if the field isn't in the required section it should generate as nullable already. Maybe my SDK is just out of date if someone already removed it from the required section.

**Comment by Rexios80** [comment]
Yeah that's definitely what happened. Thank you for the PR, but this is not a necessary change since the `roleRestricted` is already not in the required section. My bad for not using the latest version of the spec.

**Comment by ariesclark** [comment]
To confirm, the lack of a property doesn't mean it can't be null, ``{ "foo": null }`` is nullable, while ``{}`` (without foo) is optional (not in required property list). If it can exist at all, in a nullish state, it should be marked as nullable.

**Comment by Rexios80** [comment]
The exception I pasted in that issue was that the key was not in the json, not that the key was there but the value was null

**Comment by Rexios80** [comment]
Also I'm not sure any language can differentiate between a missing key and a null value besides throwing an exception if the key is missing which is probably never what we want. I'm almost thinking we should not use the required section at all and just mark fields as nullable instead, but that would be a large refactor.

**Pull request closed without merging**
