### PR TITLE
Add missing `/invite/myself/to/` endpoint

### LINKED ISSUE #157: Missing /invite/myself/to/

### PR DESCRIPTION
**Pull request by Katistic**
Fixes #157 
I might have missed something, please test the pages build :)

### CODE REVIEW

**Review by Foorack — CHANGES_REQUESTED** [review]
Missing the path from `paths.yml`

**Comment by Foorack** [comment]
@Katistic Do you have time to please look at this? If the path is missing from `paths.yml` then the entire endpoint will not be loaded.

**Comment by Miner28** [comment]
Just checked through the spec, /invite/myself/to is already implemented 🤔 Just for whatever reason its not in invite.yaml but instances.yaml @Foorack

**Comment by Miner28** [comment]
Also paths.yaml does already include this endpoint

**Comment by Miner28** [comment]
Wait, this endpoint is already documented in invites.yaml, I didn't check the changes in this PR. 
There would be a duplicate now.

**Pull request closed without merging**
