### PR TITLE
Remove regex patterns

### PR DESCRIPTION
**Pull request by JU5TDIE**

### CODE REVIEW

**Comment by Rexios80** [comment]
Can we just remove these instead?

**Comment by Rexios80** [comment]
I would like to remove any and all data validation from the spec if the other contributors are okay with it. The way I see it, it can only ever cause issues and not really benefit anything. I think @Foorack and I discussed this before and they wanted to keep it so we know when things are outside of expected parameters, but then we just end up with broken libraries in production code and we have to fix them.

**Comment by Foorack** [comment]
@Rexios80 
> but then we just end up with broken libraries in production 
That is a very good argument. I still wish they could stay, but with the instability of VRC API it is not an option. I am in favour of removing them.

**Comment by ariesclark** [comment]
Superseded by #264.

**Pull request closed without merging**
