### PR TITLE
Notifications from the websocket have `receiverUserId` and do not have `seen`

### PR DESCRIPTION
**Pull request by Rexios80**

### CODE REVIEW

**Comment by Rexios80** [comment]
image

**Comment by Rexios80** [comment]
Are we going to merge this?

**Comment by Foorack** [comment]
> Are we going to merge this?

IIRC it was **you** who asked me to wait on this for you to do a little more testing. Can we merge it now?

**Comment by Rexios80** [comment]
Oh. Yeah that testing is done.

**Review by Foorack — APPROVED** [review]

**Pull request merged**
